name: 'code-analysis-action'
description: 'Run code analysis for Plone backend packages'
author: 'Plone Community'
branding:
  icon: 'code'
  color: 'blue'
inputs:
  base_dir:
    description: 'Base directory'
    required: false
    default: ""
  check:
    description: 'Check to be used'
    required: false
    default: ""
  path:
    description: 'Path to check'
    required: false
    default: ""
  log_level:
    description: 'Log level'
    required: false
    default: "INFO"
runs:
  using: 'docker'
  image: 'docker://plone/code-quality:2'
  args:
    - check
    - ${{ inputs.check }}
    - ${{ inputs.path }}
  env:
    BASE_DIR: ${{ inputs.base_dir }}
    LOG_LEVEL: ${{ inputs.log_level }}
